/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author Iraklis
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Cadnovolider = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_DeslogarPrincipal = new javax.swing.JButton();
        fundo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("O Poder é Seu");
        setResizable(false);
        getContentPane().setLayout(null);

        btn_Cadnovolider.setFont(new java.awt.Font("Viner Hand ITC", 2, 18)); // NOI18N
        btn_Cadnovolider.setText("Nomear novo Líder");
        btn_Cadnovolider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadnovoliderActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cadnovolider);
        btn_Cadnovolider.setBounds(60, 20, 200, 50);

        jButton2.setFont(new java.awt.Font("Viner Hand ITC", 2, 18)); // NOI18N
        jButton2.setText("Admnistrar Horda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 90, 200, 50);

        jButton3.setFont(new java.awt.Font("Viner Hand ITC", 2, 18)); // NOI18N
        jButton3.setText("Soldados");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(60, 160, 200, 50);

        btn_DeslogarPrincipal.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        btn_DeslogarPrincipal.setText("Deslogar");
        btn_DeslogarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeslogarPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_DeslogarPrincipal);
        btn_DeslogarPrincipal.setBounds(60, 230, 200, 50);

        fundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo3.jpg"))); // NOI18N
        getContentPane().add(fundo2);
        fundo2.setBounds(-70, 0, 600, 370);

        setSize(new java.awt.Dimension(330, 345));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadnovoliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadnovoliderActionPerformed
       
        TelaNovoLider tnl = new TelaNovoLider();
            tnl.setVisible(true);
            
        dispose();
    }//GEN-LAST:event_btn_CadnovoliderActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        TelaAdmHorda tah = new TelaAdmHorda();
            tah.setVisible(true);
            
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        TelaSoldados tss = new TelaSoldados();
            tss.setVisible(true);
            
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_DeslogarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeslogarPrincipalActionPerformed
        
        TelaLogin tlg = new TelaLogin();
            tlg.setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_btn_DeslogarPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cadnovolider;
    private javax.swing.JButton btn_DeslogarPrincipal;
    private javax.swing.JLabel fundo2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
