/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import modelo.bean.LoginHorda;
import modelo.dao.HordaDAO;

/**
 *
 * @author Iraklis
 */
public class TelaIngressar extends javax.swing.JFrame {

    /**
     * Creates new form TelaIngressar
     */
    public TelaIngressar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_TituloIngressar = new javax.swing.JLabel();
        lbl_NomeIngressar = new javax.swing.JLabel();
        lbl_RacaIngressar = new javax.swing.JLabel();
        lbl_UsuarioIngressar = new javax.swing.JLabel();
        lbl_SenhaIngressar = new javax.swing.JLabel();
        btn_VoltarIngressar = new javax.swing.JButton();
        btn_Ingressar = new javax.swing.JButton();
        txt_NomeIngressar = new javax.swing.JTextField();
        txt_RacaIngressar = new javax.swing.JComboBox<>();
        txt_UsuarioIngressar = new javax.swing.JTextField();
        txt_SenhaIngressar = new javax.swing.JTextField();
        FundoTelaIngressar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saruman aguarda você!");
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_TituloIngressar.setFont(new java.awt.Font("Vivaldi", 3, 48)); // NOI18N
        lbl_TituloIngressar.setText("Ingresse à Horda");
        getContentPane().add(lbl_TituloIngressar);
        lbl_TituloIngressar.setBounds(60, 10, 380, 60);

        lbl_NomeIngressar.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        lbl_NomeIngressar.setText("Nome:");
        getContentPane().add(lbl_NomeIngressar);
        lbl_NomeIngressar.setBounds(20, 120, 70, 20);

        lbl_RacaIngressar.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        lbl_RacaIngressar.setText("Raça:");
        getContentPane().add(lbl_RacaIngressar);
        lbl_RacaIngressar.setBounds(20, 170, 60, 30);

        lbl_UsuarioIngressar.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        lbl_UsuarioIngressar.setText("Usuário:");
        getContentPane().add(lbl_UsuarioIngressar);
        lbl_UsuarioIngressar.setBounds(20, 230, 80, 30);

        lbl_SenhaIngressar.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        lbl_SenhaIngressar.setText("Senha:");
        getContentPane().add(lbl_SenhaIngressar);
        lbl_SenhaIngressar.setBounds(250, 230, 70, 30);

        btn_VoltarIngressar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btn_VoltarIngressar.setText("Voltar");
        btn_VoltarIngressar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarIngressarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_VoltarIngressar);
        btn_VoltarIngressar.setBounds(20, 320, 80, 30);

        btn_Ingressar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btn_Ingressar.setText("Ingressar");
        btn_Ingressar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngressarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Ingressar);
        btn_Ingressar.setBounds(350, 320, 110, 30);
        getContentPane().add(txt_NomeIngressar);
        txt_NomeIngressar.setBounds(100, 110, 360, 30);

        txt_RacaIngressar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Goblin", "Uruk-hai", "Snaga", "Warg" }));
        getContentPane().add(txt_RacaIngressar);
        txt_RacaIngressar.setBounds(100, 170, 100, 30);
        getContentPane().add(txt_UsuarioIngressar);
        txt_UsuarioIngressar.setBounds(100, 230, 110, 30);
        getContentPane().add(txt_SenhaIngressar);
        txt_SenhaIngressar.setBounds(320, 230, 140, 30);

        FundoTelaIngressar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo3.jpg"))); // NOI18N
        getContentPane().add(FundoTelaIngressar);
        FundoTelaIngressar.setBounds(0, 0, 510, 385);

        setSize(new java.awt.Dimension(497, 395));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VoltarIngressarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarIngressarActionPerformed
       
        TelaLogin log = new TelaLogin();
            log.setVisible(true);
            
        dispose();
        
    }//GEN-LAST:event_btn_VoltarIngressarActionPerformed

    private void btn_IngressarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngressarActionPerformed
       
        LoginHorda h = new LoginHorda();
        HordaDAO hordao = new HordaDAO();
        
        h.setLogin(txt_UsuarioIngressar.getText());        
        h.setSenha(txt_SenhaIngressar.getText());
        h.setNomehorda(txt_NomeIngressar.getText());        
        h.setRacahorda((String) txt_RacaIngressar.getSelectedItem());
        h.setRegiaohorda("Sem região");
        h.setOrdenshorda("Sem ordens");
        h.setStatus("Em andamento");        
               
        hordao.recrutar(h);
        
        txt_UsuarioIngressar.setText("");
        txt_SenhaIngressar.setText("");
        txt_NomeIngressar.setText("");
                             
                            
      
        
    }//GEN-LAST:event_btn_IngressarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIngressar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIngressar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIngressar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIngressar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaIngressar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FundoTelaIngressar;
    private javax.swing.JButton btn_Ingressar;
    private javax.swing.JButton btn_VoltarIngressar;
    private javax.swing.JLabel lbl_NomeIngressar;
    private javax.swing.JLabel lbl_RacaIngressar;
    private javax.swing.JLabel lbl_SenhaIngressar;
    private javax.swing.JLabel lbl_TituloIngressar;
    private javax.swing.JLabel lbl_UsuarioIngressar;
    private javax.swing.JTextField txt_NomeIngressar;
    private javax.swing.JComboBox<String> txt_RacaIngressar;
    private javax.swing.JTextField txt_SenhaIngressar;
    private javax.swing.JTextField txt_UsuarioIngressar;
    // End of variables declaration//GEN-END:variables
}
